"""Generate .env.template files from existing .env files."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List

from envguard.parser import parse_env_file
from envguard.env_auditor import _is_sensitive_key


@dataclass
class TemplateResult:
    source_path: str
    keys: List[str] = field(default_factory=list)
    sensitive_keys: List[str] = field(default_factory=list)
    output_path: str = ""

    def __bool__(self) -> bool:  # noqa: D105
        return len(self.keys) > 0


def generate_template(
    env_path: str,
    mask_sensitive: bool = True,
    placeholder: str = "",
) -> TemplateResult:
    """Parse *env_path* and return a TemplateResult describing the template."""
    env = parse_env_file(env_path)
    keys = list(env.keys())
    sensitive: List[str] = []

    lines: Dict[str, str] = {}
    for key, value in env.items():
        if mask_sensitive and _is_sensitive_key(key):
            sensitive.append(key)
            lines[key] = placeholder
        else:
            lines[key] = value

    result = TemplateResult(
        source_path=env_path,
        keys=keys,
        sensitive_keys=sensitive,
    )
    result._lines = lines  # type: ignore[attr-defined]
    return result


def render_template(result: TemplateResult) -> str:
    """Render the template as a string suitable for writing to disk."""
    lines = ["# Generated by envguard — do not commit real secrets\n"]
    for key, value in result._lines.items():  # type: ignore[attr-defined]
        lines.append(f"{key}={value}\n")
    return "".join(lines)


def write_template(result: TemplateResult, output_path: str) -> None:
    """Write the rendered template to *output_path*."""
    content = render_template(result)
    Path(output_path).write_text(content, encoding="utf-8")
    result.output_path = output_path
